stats: STATSAPI
server:
   join_leave_messages: false
addons:
   corpse_reborn:
      enabled: true
bungeecord:
   enabled: false
   voting: true
   lobbyserver: Lobby-1
   players:
     min: 4
     max: 24
mapreset:
   items: true
   arrows: true
   blocks: true
gamemodes:
   lobby: ADVENTURE
   game: SURVIVAL
   spectator: SPECTATOR
   leave: SURVIVAL
game:
   points:
     traitor:
       kill_innocent: 1
       kill_detective: 3
     detective:
       kill_traitor: 2
   karma:
     INNOCENT:
       kill_innocent: -50
       kill_detective: -150
       kill_traitor: 30
     DETECTIVE:
       kill_innocent: -50
       kill_detective: -150
       kill_traitor: 30
     TRAITOR:
       kill_innocent: 20
       kill_detective: 50
       kill_traitor: -150     
   hunger: false
   itemdrop: true
   regenerate: false
   interact:
     potions: true
     bow: true
     pressure_plates: true
     blocks:
       - ACACIA_DOOR
       - BIRCH_DOOR
       - DARK_OAK_DOOR
       - JUNGLE_DOOR
       - OAK_DOOR
       - SPRUCE_DOOR
       - ACACIA_BUTTON
       - BIRCH_BUTTON
       - DARK_OAK_BUTTON
       - JUNGLE_BUTTON
       - OAK_BUTTON
       - SPRUCE_BUTTON
       - LEVER
   barrier:
     leave: true
     leave-damage: 4
     spectator-leave: false
   countdowns:
     lobby:
       start: 60
       full: 15
     game:
       warmup: 45
       game: 900
       end: 30
   ratio:
     innocent: 50
     traitor: 30
     detective: 20