bungeecord:
   enabled: false
   voting: true
   lobbyserver: Lobby-1
gamemodes:
   lobby: ADVENTURE
   game: SURVIVAL
   spectator: ADVENTURE
   leave: SURVIVAL
game:
   hunger: false
   itemdrop: false