bungeecord:
   enabled: false
   voting: true
   lobbyserver: Lobby-1
   players:
     min: 4
     max: 24
gamemodes:
   lobby: ADVENTURE
   game: SURVIVAL
   spectator: ADVENTURE
   leave: SURVIVAL
game:
   hunger: false
   itemdrop: false
   countdowns:
     lobby:
       start: 60
       full: 15
   ratio:
     innocent: 50
     traitor: 30
     detective: 20