name: eTTT
version: 4.0.0.3 indev
description: eTTT Plugin by melays.de
author: melays
website: http://melays.de/
main: de.melays.ettt.Main
softdepend: [StatsAPI , CorpseReborn]
api-version: 1.14
commands:
  ttt:
    description: Manage the eTTT Plugin
    aliases: [ettt , troubleinterroristtown]
    usage: /ttt help
  tttsetup:
    description: Manage the eTTT Plugin
    aliases: [etttsetup , ttt-setup , ettt-setup]
    usage: /ttt help