roles:
  none: "&7None"
  spectator: "&7Spectator"
  innocent:
    display: "&aInnocent"
  traitor:
    display: "&cTraitor"
  detective:
    display: "&9Detective"
addons:
  corpse_reborn:
    corpse_name: "&7Dead Body"
game:
  items:
    roleselector:
      enabled: true
      slot: 0
    leave:
      enabled: true
      slot: 8
    vote:
      enabled: true
      slot: 4
  actionbar:
    game: "&c- &eRole: %role% &c-"
  tab:
    spectators:
      prefix: "&8&o"
      suffix: ""    
    none:
      prefix: "&e&o"
      suffix: ""
    innocent:
      prefix: "&e"
      suffix: ""
    innocent_traitor_view:
      prefix: "&a"
      suffix: ""    
    traitor:
      prefix: "&8[&4T&8] &c"
      suffix: ""
    detective:
      prefix: "&9"
      suffix: ""
  titles:
    win:
      traitor: "&cTraitors won!"
      innocent: "&aInnocent won!"
      you_won: "&aCongratulations!"
      you_lost: "&cBetter luck next time!"
    roles:
      traitor:
        title: "&c&lTRAITOR"
        subtitle: "&eTry to kill as much Innocents as possible!"
        fadein: 0
        show: 60
        fadeout: 20
      detective:
        title: "&9&lDETECTIVE"
        subtitle: "&eFind out who are the Traitors!"
        fadein: 0
        show: 60
        fadeout: 20
      innocent:
        title: "&a&lINNOCENT"
        subtitle: "&eFind out who is are the Traitors!"
        fadein: 0
        show: 60
        fadeout: 20
    warning:
      play-area:
        title: "&4&l&oOUT OF MAP"
        subtitle: "&cPlease return to the play-arena!"
        fadein: 0
        show: 10
        fadeout: 10
  scoreboard:
    lobby:
      title: "&c- &e&leTTT &c-"
      timer:
        divider: "&8:"
        minutes: "&c- &7%minutes%"
        seconds: "&7%seconds%"
      content:
      - ""
      - "&eArena:"
      - "&c- &a%arena%"
      - "  "
      - "&eTimer:"
      - time-line
      - "   "
    game:
      playing:
        title: "&c- &e&leTTT &c-"
        timer:
          divider: "&8:"
          minutes: "&c- &7%minutes%"
          seconds: "&7%seconds%"
        content:
        - ""
        - "&eRole:"
        - "&c- &a%role%"        
        - " "
        - "&ePlayers:"
        - "&c- &a%alive% alive"        
        - "  "        
        - "&eArena:"
        - "&c- &a%arena%"
        - "   "
        - "&eTimer:"
        - time-line
        - "    "
      spectating:
        title: "&c- &e&leTTT &c-"
        timer:
          divider: "&8:"
          minutes: "&c- &7%minutes%"
          seconds: "&7%seconds%"
        content:
        - ""
        - "&eSpectating:"
        - "&c- &a%specs% Players"        
        - " "
        - "&ePlayers:"
        - "&c- &a%alive% alive"        
        - "  "
        - "&eArena:"
        - "&c- &a%arena%"
        - "   "
        - "&eTimer:"
        - time-line
        - "    "
  inventory:
    shop:
      traitor_title: "&cTraitorshop"
      detective_shop: "&9Detectiveshop"
    roleselection:
      title: "&eRole selection"
    voting:
      title: "&eMap Voting"
      item-title: "&a%display%"
      item-lore: "&a%votes% &evotes"
    lootchest:
      title: "&8Chest"
    enderchest:
      title: "&8Enderchest"
