roles:
  none: "None"
  innocent:
    display: "&aInnocent"
  traitor:
    display: "&cTraitor"
  detective:
    display: "&9Detective"
game:
  items:
    roleselector:
      enabled: true
      slot: 0
    leave:
      enabled: true
      slot: 8
    vote:
      enabled: true
      slot: 4
  scoreboard:
    lobby:
      title: "&c- &e&leTTT &c-"
      timer:
        divider: "&8:"
        minutes: "&c- &7%minutes%"
        seconds: "&7%seconds%"
      content:
      - ""
      - "&eArena:"
      - "&c- &a%arena%"
      - "  "
      - "&eTimer:"
      - time-line
      - "   "
  inventory:
    roleselection:
      title: "&eRole selection"